/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    service: Service;
    product: Product;
    referans: Referan;
    page: Page;
    faq: Faq;
    post: Post;
    job: Job;
    project: Project;
    richPage: RichPage;
    solution: Solution;
    teamMember: TeamMember;
    document: Document;
    formGonderimi: FormGonderimi;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
    referans: ReferansSelect<false> | ReferansSelect<true>;
    page: PageSelect<false> | PageSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    post: PostSelect<false> | PostSelect<true>;
    job: JobSelect<false> | JobSelect<true>;
    project: ProjectSelect<false> | ProjectSelect<true>;
    richPage: RichPageSelect<false> | RichPageSelect<true>;
    solution: SolutionSelect<false> | SolutionSelect<true>;
    teamMember: TeamMemberSelect<false> | TeamMemberSelect<true>;
    document: DocumentSelect<false> | DocumentSelect<true>;
    formGonderimi: FormGonderimiSelect<false> | FormGonderimiSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en') | ('tr' | 'en')[];
  globals: {
    siteSettings: SiteSetting;
    navigation: Navigation;
    homePage: HomePage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: 'tr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: number;
  isKolu: 'yazilim' | 'danismanlik' | 'muhendislik';
  baslik: string;
  ozet?: string | null;
  chips?:
    | {
        etiket?: string | null;
        id?: string | null;
      }[]
    | null;
  girisLead?: string | null;
  girisParagraflar?:
    | {
        paragraf?: string | null;
        id?: string | null;
      }[]
    | null;
  altHizmetler?:
    | {
        icon?:
          | (
              | 'shield-check'
              | 'clipboard'
              | 'ruler'
              | 'hard-hat'
              | 'building'
              | 'key'
              | 'droplet'
              | 'wall'
              | 'wrench'
              | 'refresh'
              | 'code'
              | 'flame'
              | 'gauge'
              | 'document'
            )
          | null;
        baslik?: string | null;
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sıra, listedeki diziliş ile belirlenir (01, 02, ...).
   */
  surec?:
    | {
        baslik?: string | null;
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  sira?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: number;
  /**
   * Örn: yanginpro veya mekanikpro
   */
  slug: string;
  ad: string;
  /**
   * Kapalıysa ürün sitede (liste ve detay) gösterilmez.
   */
  yayinda?: boolean | null;
  slogan?: string | null;
  aciklama?: string | null;
  ozellikler?:
    | {
        icon?:
          | (
              | 'shield-check'
              | 'clipboard'
              | 'ruler'
              | 'hard-hat'
              | 'building'
              | 'key'
              | 'droplet'
              | 'wall'
              | 'wrench'
              | 'refresh'
              | 'code'
              | 'flame'
              | 'gauge'
              | 'document'
            )
          | null;
        baslik?: string | null;
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  hedefKitle?:
    | {
        madde?: string | null;
        id?: string | null;
      }[]
    | null;
  ekranGorselleri?:
    | {
        gorsel?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sira?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referans".
 */
export interface Referan {
  id: number;
  ad: string;
  /**
   * URL eki. Boş bırakılırsa addan otomatik üretilir.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  anasayfada?: boolean | null;
  gorus?: {
    metin?: string | null;
    kisi?: string | null;
    unvan?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page".
 */
export interface Page {
  id: number;
  /**
   * hakkimizda, vizyon-misyon veya kalite-belgeler
   */
  slug: string;
  baslik: string;
  altBaslik?: string | null;
  chips?:
    | {
        etiket?: string | null;
        id?: string | null;
      }[]
    | null;
  girisLead?: string | null;
  girisParagraflar?:
    | {
        paragraf?: string | null;
        id?: string | null;
      }[]
    | null;
  vizyonBaslik?: string | null;
  vizyonMetin?: string | null;
  misyonBaslik?: string | null;
  misyonMetin?: string | null;
  kartlarEyebrow?: string | null;
  kartlarBaslik?: string | null;
  kartlarAciklama?: string | null;
  kartlar?:
    | {
        icon?:
          | (
              | 'shield-check'
              | 'clipboard'
              | 'ruler'
              | 'hard-hat'
              | 'building'
              | 'key'
              | 'droplet'
              | 'wall'
              | 'wrench'
              | 'refresh'
              | 'code'
              | 'flame'
              | 'gauge'
              | 'document'
            )
          | null;
        baslik?: string | null;
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  kategori?: ('genel' | 'yazilim' | 'danismanlik' | 'muhendislik') | null;
  soru: string;
  cevap?: string | null;
  sira?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post".
 */
export interface Post {
  id: number;
  slug: string;
  baslik: string;
  tarih?: string | null;
  kapak?: (number | null) | Media;
  ozet?: string | null;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  etiketler?:
    | {
        etiket?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job".
 */
export interface Job {
  id: number;
  slug: string;
  baslik: string;
  lokasyon?: string | null;
  tip?: string | null;
  aciklama?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  aktif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  id: number;
  slug: string;
  baslik: string;
  musteri?: string | null;
  /**
   * Bu proje bir referans kaydına bağlanırsa referans detay sayfasında listelenir ve proje detayında referansa link verilir. Opsiyonel.
   */
  referans?: (number | null) | Referan;
  isKolu?: ('yazilim' | 'danismanlik' | 'muhendislik') | null;
  durum?: ('devam-eden' | 'tamamlandi') | null;
  yil?: number | null;
  il?: string | null;
  kapsam?: string | null;
  ozet?: string | null;
  aciklama?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gorseller?:
    | {
        gorsel?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  oneCikan?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "richPage".
 */
export interface RichPage {
  id: number;
  slug: string;
  kategori?: ('legal' | 'kurumsal' | 'redwall') | null;
  baslik: string;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sonGuncelleme?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution".
 */
export interface Solution {
  id: number;
  slug: string;
  baslik: string;
  ozet?: string | null;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ikon?:
    | (
        | 'shield-check'
        | 'clipboard'
        | 'ruler'
        | 'hard-hat'
        | 'building'
        | 'key'
        | 'droplet'
        | 'wall'
        | 'wrench'
        | 'refresh'
        | 'code'
        | 'flame'
        | 'gauge'
        | 'document'
      )
    | null;
  hedefKitle?: string | null;
  sira?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMember".
 */
export interface TeamMember {
  id: number;
  ad: string;
  unvan?: string | null;
  foto?: (number | null) | Media;
  bio?: string | null;
  linkedin?: string | null;
  sira?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document".
 */
export interface Document {
  id: number;
  baslik: string;
  aciklama?: string | null;
  dosya?: (number | null) | Media;
  kategori?: string | null;
  sira?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formGonderimi".
 */
export interface FormGonderimi {
  id: number;
  tur: 'iletisim' | 'teklif' | 'demo' | 'kvkk';
  ad: string;
  email: string;
  telefon?: string | null;
  kurum?: string | null;
  isKolu?: string | null;
  il?: string | null;
  metrekare?: string | null;
  urun?: string | null;
  basvuruSahibiSifati?: string | null;
  talepTuru?: string | null;
  kvkkOnay?: boolean | null;
  mesaj?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'service';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'product';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'referans';
        value: number | Referan;
      } | null)
    | ({
        relationTo: 'page';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'post';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'job';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'project';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'richPage';
        value: number | RichPage;
      } | null)
    | ({
        relationTo: 'solution';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'teamMember';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'document';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'formGonderimi';
        value: number | FormGonderimi;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  isKolu?: T;
  baslik?: T;
  ozet?: T;
  chips?:
    | T
    | {
        etiket?: T;
        id?: T;
      };
  girisLead?: T;
  girisParagraflar?:
    | T
    | {
        paragraf?: T;
        id?: T;
      };
  altHizmetler?:
    | T
    | {
        icon?: T;
        baslik?: T;
        aciklama?: T;
        id?: T;
      };
  surec?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        id?: T;
      };
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  slug?: T;
  ad?: T;
  yayinda?: T;
  slogan?: T;
  aciklama?: T;
  ozellikler?:
    | T
    | {
        icon?: T;
        baslik?: T;
        aciklama?: T;
        id?: T;
      };
  hedefKitle?:
    | T
    | {
        madde?: T;
        id?: T;
      };
  ekranGorselleri?:
    | T
    | {
        gorsel?: T;
        id?: T;
      };
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referans_select".
 */
export interface ReferansSelect<T extends boolean = true> {
  ad?: T;
  slug?: T;
  logo?: T;
  anasayfada?: T;
  gorus?:
    | T
    | {
        metin?: T;
        kisi?: T;
        unvan?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_select".
 */
export interface PageSelect<T extends boolean = true> {
  slug?: T;
  baslik?: T;
  altBaslik?: T;
  chips?:
    | T
    | {
        etiket?: T;
        id?: T;
      };
  girisLead?: T;
  girisParagraflar?:
    | T
    | {
        paragraf?: T;
        id?: T;
      };
  vizyonBaslik?: T;
  vizyonMetin?: T;
  misyonBaslik?: T;
  misyonMetin?: T;
  kartlarEyebrow?: T;
  kartlarBaslik?: T;
  kartlarAciklama?: T;
  kartlar?:
    | T
    | {
        icon?: T;
        baslik?: T;
        aciklama?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  kategori?: T;
  soru?: T;
  cevap?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post_select".
 */
export interface PostSelect<T extends boolean = true> {
  slug?: T;
  baslik?: T;
  tarih?: T;
  kapak?: T;
  ozet?: T;
  icerik?: T;
  etiketler?:
    | T
    | {
        etiket?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job_select".
 */
export interface JobSelect<T extends boolean = true> {
  slug?: T;
  baslik?: T;
  lokasyon?: T;
  tip?: T;
  aciklama?: T;
  aktif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_select".
 */
export interface ProjectSelect<T extends boolean = true> {
  slug?: T;
  baslik?: T;
  musteri?: T;
  referans?: T;
  isKolu?: T;
  durum?: T;
  yil?: T;
  il?: T;
  kapsam?: T;
  ozet?: T;
  aciklama?: T;
  gorseller?:
    | T
    | {
        gorsel?: T;
        id?: T;
      };
  oneCikan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "richPage_select".
 */
export interface RichPageSelect<T extends boolean = true> {
  slug?: T;
  kategori?: T;
  baslik?: T;
  icerik?: T;
  sonGuncelleme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution_select".
 */
export interface SolutionSelect<T extends boolean = true> {
  slug?: T;
  baslik?: T;
  ozet?: T;
  icerik?: T;
  ikon?: T;
  hedefKitle?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamMember_select".
 */
export interface TeamMemberSelect<T extends boolean = true> {
  ad?: T;
  unvan?: T;
  foto?: T;
  bio?: T;
  linkedin?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document_select".
 */
export interface DocumentSelect<T extends boolean = true> {
  baslik?: T;
  aciklama?: T;
  dosya?: T;
  kategori?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formGonderimi_select".
 */
export interface FormGonderimiSelect<T extends boolean = true> {
  tur?: T;
  ad?: T;
  email?: T;
  telefon?: T;
  kurum?: T;
  isKolu?: T;
  il?: T;
  metrekare?: T;
  urun?: T;
  basvuruSahibiSifati?: T;
  talepTuru?: T;
  kvkkOnay?: T;
  mesaj?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  sirketAdi: string;
  iletisim?: {
    tel?: string | null;
    email?: string | null;
    adres?: string | null;
  };
  /**
   * Tam URL girin (https://...). Boş bırakılan platform footer'da gösterilmez.
   */
  sosyal?: {
    linkedin?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    x?: string | null;
    facebook?: string | null;
    /**
     * Örn: https://wa.me/90XXXXXXXXXX
     */
    whatsapp?: string | null;
  };
  calismaSaatleri?: string | null;
  istatistikler?:
    | {
        deger?: string | null;
        etiket?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    baslik?: string | null;
    aciklama?: string | null;
  };
  /**
   * Şirketin resmi yasal tanımlayıcı bilgileri. Yerelleştirilmez.
   */
  kunye?: {
    mersisNo?: string | null;
    ticaretSicilNo?: string | null;
    kepAdresi?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerLinks?:
    | {
        etiket?: string | null;
        href?: string | null;
        alt?:
          | {
              etiket?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerKolonlari?:
    | {
        baslik?: string | null;
        linkler?:
          | {
              etiket?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  heroBaslik: string;
  heroAltMetin?: string | null;
  heroBirincilCta?: {
    etiket?: string | null;
    href?: string | null;
  };
  heroIkincilCta?: {
    etiket?: string | null;
    href?: string | null;
  };
  oneCikanUrun?: (number | null) | Product;
  yaklasim?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  sirketAdi?: T;
  iletisim?:
    | T
    | {
        tel?: T;
        email?: T;
        adres?: T;
      };
  sosyal?:
    | T
    | {
        linkedin?: T;
        instagram?: T;
        youtube?: T;
        x?: T;
        facebook?: T;
        whatsapp?: T;
      };
  calismaSaatleri?: T;
  istatistikler?:
    | T
    | {
        deger?: T;
        etiket?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
      };
  kunye?:
    | T
    | {
        mersisNo?: T;
        ticaretSicilNo?: T;
        kepAdresi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        etiket?: T;
        href?: T;
        alt?:
          | T
          | {
              etiket?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerKolonlari?:
    | T
    | {
        baslik?: T;
        linkler?:
          | T
          | {
              etiket?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroBaslik?: T;
  heroAltMetin?: T;
  heroBirincilCta?:
    | T
    | {
        etiket?: T;
        href?: T;
      };
  heroIkincilCta?:
    | T
    | {
        etiket?: T;
        href?: T;
      };
  oneCikanUrun?: T;
  yaklasim?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}